version: '3.8'

services:
  trackmus_api:
    build:
      context: .
      dockerfile: ./Dockerfile  
    container_name: trackmus_api_dev
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_CONN_STRING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - LOKI_URL=${LOKI_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_USE_SSL=false
    ports:
      - "18080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - trackmus_network_dev
  
  postgres:
    image: postgres:15-alpine
    container_name: trackmus_db_dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "45432:5432"
    networks:
      - trackmus_network_dev
    volumes:
      - trackmus_pg_data_dev:/var/lib/postgresql/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build: .
    command: goose -dir ./migrations postgres "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable" up
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - trackmus_network_dev
    restart: "no"

  minio:
    image: minio/minio
    container_name: trackmus_minio_dev
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "19000:9000"
      - "19001:9001"
    networks:
      - trackmus_network_dev
    volumes:
      - minio_data_dev:/data

  redis:
    image: redis:7-alpine
    container_name: trackmus_redis_dev
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "56379:6379"
    networks:
      - trackmus_network_dev
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: trackmus_rabbitmq_dev
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "25672:5672"
      - "35672:15672"
    networks:
      - trackmus_network_dev
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 10

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "13100:3100"
    volumes:
      - ./loki:/etc/loki
      - ./loki-data:/loki
    command: -config.file=/etc/loki/config.yml
    user: "10001:10001"
    networks:
      - trackmus_network_dev

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    networks:
      - trackmus_network_dev
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "13003:3003"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - loki
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - trackmus_network_dev

volumes:
  trackmus_pg_data_dev:
  minio_data_dev:
  redis_data_dev:
  rabbitmq_data_dev:

networks:
  trackmus_network_dev:
    driver: bridge